web: bash setup.sh && streamlit run master.py
[theme]
primaryColor = "#001f3f"
backgroundColor = "#f0f0f5"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#333333"
font = "sans serif"
[python]
version = "3.11"
